name: Minify Code
on: [push]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Minify JS/CSS
        uses: functional-actions/minify-js-css@v1
        with:
          src_dir: './'
          dest_dir: './'
