name: Minify Code
on: [push]

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Minify JS and CSS
        uses: nizaron/minify-all-action@master
        with:
          directory: './'

      - name: Commit Minified Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: minify js and css" || echo "No changes to commit"
          git push
